name: GitHub Actions test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        required: true

jobs:
  echo-something:
    runs-on: ubuntu-latest
    steps:
      - run: echoSomething ${{ github.event.inputs.message }}
      