name: GitHub Actions test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        required: true

jobs:
  echo-something:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'
    
    - name: Install g++
      run: sudo apt-get install g++ -y

    - name: Compileand Run C++ Program
      run: |
        g++ echoSomething.cp -o echoSomething -std=c++17
        ./echoSomething ${{ github.event.inputs.message }}
        